# Generated by Django 4.2.7 on 2024-03-16 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('c_logo', models.ImageField(upload_to='static/img/company_profile_pics', validators=[django.core.validators.validate_image_file_extension])),
                ('c_ph_no', models.IntegerField()),
                ('park_option', models.CharField(max_length=25)),
                ('timeA', models.TimeField()),
                ('timeZ', models.TimeField()),
                ('c_location', models.CharField(max_length=40)),
                ('c_desc', models.TextField(max_length=500)),
                ('c_email', models.CharField(max_length=40, unique=True)),
                ('c_pswd', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='parker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph_no', models.IntegerField()),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='parkinglot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_type', models.CharField(max_length=20)),
                ('park_id', models.IntegerField()),
                ('park_cname', models.CharField(max_length=20)),
                ('park_c_location', models.CharField(max_length=40)),
                ('park_c_email', models.CharField(max_length=40)),
                ('park_c_ph_no', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('no_slots', models.IntegerField()),
                ('park_price', models.FloatField()),
                ('extra_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('prof_pic', models.ImageField(upload_to='')),
                ('job_desc', models.CharField(max_length=40)),
                ('s_ph_no', models.IntegerField()),
                ('c_email', models.CharField(max_length=40)),
                ('c_location', models.CharField(max_length=40)),
                ('s_email', models.CharField(max_length=40)),
                ('s_password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='parking_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_price', models.FloatField()),
                ('no_slots', models.IntegerField()),
                ('no_hrs', models.IntegerField()),
                ('booked_date', models.DateTimeField()),
                ('park_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parkinglot')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parker')),
            ],
        ),
    ]
