# Generated by Django 4.2.5 on 2024-03-17 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='prof_pic',
            field=models.ImageField(upload_to='static/img/staff_profile_pics', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
