# Generated by Django 4.2.5 on 2024-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_staff_prof_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_booking',
            name='no_slots',
        ),
    ]
