# Generated by Django 4.2.5 on 2024-03-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_parking_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_booking',
            old_name='email',
            new_name='Email',
        ),
    ]
