# Generated by Django 4.2.5 on 2024-03-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_email_parking_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_booking',
            name='no_slot',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
