# Generated by Django 4.2.5 on 2024-03-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_parking_booking_no_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
