# Generated by Django 4.2.5 on 2024-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_parkinglot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_booking',
            name='booked_date',
            field=models.DateField(),
        ),
    ]
