# Generated by Django 4.2.5 on 2024-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_parking_booking_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_booking',
            name='no_slot',
            field=models.CharField(max_length=10),
        ),
    ]
