# Generated by Django 4.2.5 on 2024-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_parking_booking_no_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_booking',
            name='booked_date',
            field=models.TextField(max_length=10),
        ),
    ]
