# Generated by Django 4.2.5 on 2024-03-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_parking_booking_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_booking',
            name='no_slot',
        ),
        migrations.AddField(
            model_name='parking_booking',
            name='end_time',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking_booking',
            name='start_time',
            field=models.TextField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
