# Generated by Django 4.2.5 on 2024-03-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_parking_booking_no_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_booking',
            name='booked_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parking_booking',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parking_booking',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
