# Generated by Django 4.2.5 on 2024-04-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_parking_booking_booked_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='conv_parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.TextField(max_length=20)),
                ('stock_item', models.IntegerField()),
                ('park_price', models.FloatField()),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
