# Generated by Django 4.2.5 on 2024-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_conv_parking_park_date_alter_conv_parking_park_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conv_parking',
            name='park_email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
