# Generated by Django 4.2.5 on 2024-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_conv_parking_park_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conv_parking',
            name='park_name',
            field=models.CharField(max_length=40),
        ),
    ]
