# Generated by Django 4.2.5 on 2024-04-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_conv_parking_park_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='conv_parking_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=40)),
                ('park_date', models.CharField(max_length=10)),
                ('stock_item', models.IntegerField()),
                ('park_price', models.FloatField()),
                ('park_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parkinglot')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parker')),
            ],
        ),
    ]
