# Generated by Django 4.2.5 on 2024-04-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_conv_parking_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conv_parking_booking',
            name='park_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.conv_parking'),
        ),
    ]
