# Generated by Django 4.2.5 on 2024-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_conv_parking_booking_park_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='park_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='park_slots',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
