# Generated by Django 4.2.5 on 2024-05-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_conv_parking_park_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conv_parking_booking',
            name='phone_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
