# Generated by Django 4.2.5 on 2024-05-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_conv_parking_booking_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conv_parking_booking',
            old_name='stock_item',
            new_name='no_slots',
        ),
    ]
