# Generated by Django 4.2.5 on 2024-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_stock_item_conv_parking_booking_no_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='park_option',
            field=models.TextField(max_length=25),
        ),
    ]
