# Generated by Django 4.2.5 on 2024-05-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_company_park_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parking_booking',
        ),
        migrations.DeleteModel(
            name='parkinglot',
        ),
    ]
