# Generated by Django 4.2.5 on 2024-05-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_delete_parking_booking_delete_parkinglot'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkinglot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_type', models.CharField(max_length=20)),
                ('park_id', models.IntegerField()),
                ('park_cname', models.CharField(max_length=20)),
                ('park_c_location', models.CharField(max_length=40)),
                ('park_c_email', models.CharField(max_length=40)),
                ('park_c_ph_no', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('no_slots', models.IntegerField()),
                ('park_price', models.FloatField()),
                ('extra_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='parking_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_price', models.FloatField()),
                ('no_hrs', models.IntegerField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=40)),
                ('booked_date', models.CharField(max_length=10)),
                ('park_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parkinglot')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parker')),
            ],
        ),
    ]
